In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
print(7)

7


In [4]:
i=5

In [5]:
print(8)

8


In [6]:
i

5

In [7]:
myarr=np.array([3,4,5,6])

In [8]:
myarr

array([3, 4, 5, 6])

In [9]:
myarr[0]

3

In [10]:
myarr[0]=45

In [11]:
myarr

array([45,  4,  5,  6])

#creating arrays

#Conversion from other Python structures (i.e. lists and tuples)

In [12]:
myarray=np.array([[1,2,3],[1,2,3]])
myarray

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
myarray.dtype

dtype('int32')

In [14]:
myarray.shape

(2, 3)

In [15]:
myarray.size

6

In [16]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [17]:
n1=np.zeros((2,5))

In [18]:
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
n2=np.arange(10,20)

In [20]:
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
n3=np.arange(10,30,4)

In [22]:
n3

array([10, 14, 18, 22, 26])

In [23]:
lspace=np.linspace(1,50,10)

In [24]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [25]:
n4=np.arange(10,50,5)

In [26]:
n4

array([10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
ide=np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
n5=np.arange(99)

In [31]:
n5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
n5.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
n5.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
n5.shape

(99,)

#AXIS

In [35]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [38]:
ar.sum(axis=0)

array([12,  8,  9])

In [39]:
ar.sum(axis=1)

array([ 6, 15,  8])

#Transpose

In [40]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [41]:
ar.flat

In [42]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


#how yo find number of dimension

In [43]:
ar.ndim

2

#How to find number of elements

In [44]:
ar.size

9

#total bytes consumed

In [45]:
ar.nbytes

36

In [46]:
one=np.array([1,3,4,634,2])

In [47]:
one.argmax()

3

In [48]:
one.argmin()

0

In [49]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.argmin()

8

In [52]:
ar.argmax()

6

In [53]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [54]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [55]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [56]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

#Matrix operation

In [57]:
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
ar+ar1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  9,  9]])

In [59]:
ar*ar1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  8,  0]])

In [60]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [61]:
ar.sum()

29

In [62]:
ar.max()

7

In [63]:
ar.min()

0

#To find any elements 

In [64]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [65]:
type(np.where(ar>5))

tuple

In [66]:
np.count_nonzero(ar)

8

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [68]:
import sys

In [69]:
py_ar=[0,4,55,2]

In [70]:
np_ar=np.array(py_ar)

In [71]:
sys.getsizeof(1)*len(py_ar)

112

In [72]:
np_ar.itemsize*np_ar.size

16

#go to google and search numpy array methods and attributes(docs.scipy)